---
# tasks file for Slave

- name: Add k8s repository
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude:
      - kubelet
      - kubeadm
      - kubectl

- name: install Docker
  package:
    name: "{{  item }}"
    state: present
  with_items:
    - docker
    - iproute-tc

- name: Install Kubeadm
  yum:
    name: kubeadm
    disable_excludes: kubernetes
    state: present

- name: start docker service
  service:
    name: "{{  item  }}"
    state: started
    enabled: yes
  with_items:
    - docker
    - kubelet

- name: Change driver to systemd
  copy:
    dest: /etc/docker/daemon.json
    content: '{
               "exec-opts": ["native.cgroupdriver=systemd"]
              }'

- name: restart docker
  service:
    name: docker
    state: restarted

- ansible.posix.sysctl:
    name: "{{ item  }}"
    value: '1'
    sysctl_file: /etc/sysctl.d/k8s.conf
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables

- name: Join Worker with Master
  command: "{{  hostvars['DUMMY_HOST']['mastertoken'] }}"
  ignore_errors: yes

