---
# tasks file for Master

- name: Add k8s repository
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude:
      - kubelet
      - kubeadm
      - kubectl

- name: install Docker
  package:
    name: "{{  item }}"
    state: present
  with_items:
    - docker
    - iproute-tc

- name: Install Kubeadm
  yum:
    name: kubeadm
    disable_excludes: kubernetes
    state: present

- name: start docker service
  service:
    name: "{{  item  }}"
    state: started
    enabled: yes
  with_items:
    - docker
    - kubelet

- name: Change driver to systemd
  copy:
    dest: /etc/docker/daemon.json
    content: '{
               "exec-opts": ["native.cgroupdriver=systemd"]
              }'

- name: restart docker
  service:
    name: docker
    state: restarted

- name: download all images
  command: kubeadm config images pull

- ansible.posix.sysctl:
    name: "{{ item  }}"
    value: '1'
    sysctl_file: /etc/sysctl.d/k8s.conf
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables

- name: init kubeadm
  command: kubeadm init --pod-network-cidr=10.240.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem
  ignore_errors: yes

- name: Copy file
  copy:
    src: kubectl.sh
    dest: /
   
- name: kubectl
  command: bash /kubectl.sh
  ignore_errors: yes

- name: Generate Token
  command: kubeadm token create --print-join-command
  register: token

- name: Token for Worker Node
  debug:
    msg: "{{ token.stdout }}" 

- name: Register dummy host with variable
  add_host:
    name: "DUMMY_HOST"
    mastertoken: " {{ token.stdout }}"

- name: flannel
  command: kubectl apply  -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: Cleaning Caches on RAM
  shell: echo 3 > /proc/sys/vm/drop_caches

